# Generated by Django 4.1 on 2023-05-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('key_words', models.CharField(max_length=255)),
                ('semantic_value', models.FloatField()),
                ('fakeFlag', models.BooleanField(default=False)),
            ],
        ),
    ]
