# Generated by Django 4.1 on 2023-05-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=500)),
                ('tfidf_sum', models.FloatField()),
                ('tfidf_mean', models.FloatField()),
                ('emotions_sum', models.IntegerField()),
                ('emotions_mean', models.FloatField()),
                ('text_length', models.IntegerField()),
                ('capital_letters_count', models.IntegerField()),
                ('numbers_count', models.IntegerField()),
                ('question_marks_count', models.IntegerField()),
                ('currency_signs_count', models.IntegerField()),
                ('capital_words_count', models.IntegerField()),
                ('non_polish_char_count', models.IntegerField()),
                ('keywords_counter', models.IntegerField()),
                ('ispossible_address', models.BooleanField()),
                ('ispossible_email', models.BooleanField()),
                ('ispossible_phone_numbers', models.BooleanField()),
                ('possible_address', models.CharField(max_length=200)),
                ('possible_email', models.CharField(max_length=200)),
                ('possible_phone_numbers', models.CharField(max_length=200)),
                ('label', models.IntegerField()),
                ('prob', models.FloatField()),
                ('risk_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
