# Generated by Django 4.1 on 2023-05-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('uppercase_counter', models.IntegerField()),
                ('exclamation_mark_counter', models.IntegerField()),
                ('currency_mark_counter', models.IntegerField()),
                ('non_polish_counter', models.IntegerField()),
                ('emotional_words_counter', models.IntegerField()),
                ('possible_contact', models.CharField(max_length=255)),
                ('possible_mail', models.CharField(max_length=255)),
                ('categories', models.CharField(max_length=255)),
                ('fake_probability', models.FloatField()),
            ],
        ),
    ]
