# Generated by Django 4.1 on 2023-05-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='Predict_Flag',
            field=models.IntegerField(),
        ),
    ]
