# Generated by Django 4.1 on 2023-05-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alter_joboffer_predict_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='Explain',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='Lokalizacja',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='Predict_Flag',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='Predict_Prob',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='Typ_umowy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='Wymiar_pracy',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='capital_letters_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='capital_words_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='category_tree_item',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='currency_signs_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='dodane_data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='emotions_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='emotions_sum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='filters',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='inspiring_keywords_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='link_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='money_related_keywords_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='non_polish_char_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='numbers_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='pay_currency',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='pay_high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='pay_low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='pay_period',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='personal_info_keywords_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='possible_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='possible_email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='possible_phone_numbers',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='question_marks_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='text_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='tfidf_mean',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='tfidf_sum',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='user_profile_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='user_profile_link_hash',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
