from django.db import models
import random
import string

# Define JobOffer model
# class JobOffer(models.Model):
#     link = models.URLField()
#     text = models.TextField()
#     date = models.DateField()
#     author = models.CharField(max_length=100)
#     length = models.IntegerField()
#     uppercase_counter = models.IntegerField()
#     exclamation_mark_counter = models.IntegerField()
#     currency_mark_counter = models.IntegerField()
#     non_polish_counter = models.IntegerField()
#     emotional_words_counter = models.IntegerField()
#     possible_contact = models.CharField(max_length=255)
#     possible_mail = models.CharField(max_length=255)
#     categories = models.CharField(max_length=255)
#     fake_probability = models.FloatField()
#     risk_value = models.IntegerField(null=True, blank=True)

class JobOffer(models.Model):
    id = models.AutoField(primary_key=True)
    link = models.URLField()
    text = models.TextField()
    author = models.CharField(max_length=500)
    tfidf_sum = models.FloatField()
    tfidf_mean = models.FloatField()
    emotions_sum = models.IntegerField()
    emotions_mean = models.FloatField()
    text_length = models.IntegerField()
    capital_letters_count = models.IntegerField()
    numbers_count = models.IntegerField()
    question_marks_count = models.IntegerField()
    currency_signs_count = models.IntegerField()
    capital_words_count = models.IntegerField()
    non_polish_char_count = models.IntegerField()
    keywords_counter = models.IntegerField()
    ispossible_address = models.BooleanField()
    ispossible_email = models.BooleanField()
    ispossible_phone_numbers = models.BooleanField()
    possible_address = models.CharField(max_length=200)
    possible_email = models.CharField(max_length=200)
    possible_phone_numbers = models.CharField(max_length=200)
    label = models.IntegerField()
    prob = models.FloatField()
    risk_value = models.IntegerField(null=True, blank=True)